name: Node:js Cl

on:
 push:
  branches:
   -main
pull_reqest:
 branches:
  -main

jobs:
 build:

  runs-on: ubuntu-latest

strategy:
 matrix:
  node-version: [20.x]

steps:
-name: cheskout repository
 uses: actions/checkout@v3

-name: set upNode.js
 uses: actions/setup-node@v3
with:
 node-version: ${{ matrix.node-version }}

 -name: instrall dependencies
 run: npm install

 -name: start application 
 run: npm start
